#ifndef BADUSB_BUILTIN_SCRIPT_H
#define BADUSB_BUILTIN_SCRIPT_H

#define BADUSB_BUILTIN_SCRIPT_NAME "Ghost Art (Built-in)"

static const char badusb_builtin_script[] =
    "REM PhantomESP - Opens Notepad and types ASCII ghost art\n"
    "GUI r\n"
    "DELAY 500\n"
    "STRING notepad\n"
    "ENTER\n"
    "DELAY 1000\n"
    "STRING                                                                                                                                                                                                        \n"
    "ENTER\n"
    "STRING                                                                                                                                                                                                        \n"
    "ENTER\n"
    "STRING                                                                                                                                                                                                        \n"
    "ENTER\n"
    "STRING                                                                                                                            @                                                                            \n"
    "ENTER\n"
    "STRING                                                                                                                          @@@                                                                            \n"
    "ENTER\n"
    "STRING                                                                                                                          @@                                                                             \n"
    "ENTER\n"
    "STRING                                                                                                                         @@                                                                              \n"
    "ENTER\n"
    "STRING                                                                  %@                                                    @@                                         %@                                    \n"
    "ENTER\n"
    "STRING                                                                  @@                                      @@@@@@@@@@@@@@@@@@@@@@@@@@@          %%%%@@@@@@@   @@@@@@%@@                                   \n"
    "ENTER\n"
    "STRING                                                                %@%                                     @@%@@@@@@     @@@@@@@@@@@@%@@@@@@@@@@@%@%@       @@@@@   @@@%                                    \n"
    "ENTER\n"
    "STRING                                                              @@@                @%%@@@%@@@%%%@@@@@@@@@@@@     @@  @@@@@@  @@@@@@@%  @@@@  @@%%@@@@@@%@@@@@@  @@@@                                       \n"
    "ENTER\n"
    "STRING                                                     %@@@@@@@@@   @@@@@@@@ @@@@@@@@@@@@@@@@%   @@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%@ @@@@@@@@@@@                                          \n"
    "ENTER\n"
    "STRING                                                %@@@@@    %@@@@@@@@   @@@@@@@        %@@@@@%@@         %%@@@@@@@%      @@@         @@             @@@@@@%                                                \n"
    "ENTER\n"
    "STRING                                             %@@@    %@@@@@@@%      @@@@@@@@@@@@@@@@@%   @@@@@@@@@@@@@%@                                        @@@%@@                                                   \n"
    "ENTER\n"
    "STRING                                            @@@@@@@@@     %@@      @@                                                                         @@@ @@@                                                    \n"
    "ENTER\n"
    "STRING                                                            @@%                                                                              @@%@@%                                                      \n"
    "ENTER\n"
    "STRING                                                             @@                                                                             @@@@@                                                        \n"
    "ENTER\n"
    "STRING                                                           %@%                                                                              @@%                                                          \n"
    "ENTER\n"
    "STRING                                                        %@%                                                                                                                                             \n"
    "ENTER\n"
    "STRING                                  @@                %@@@@                                                                                                                                                \n"
    "ENTER\n"
    "STRING                                   @@@@%@%%@%@@@@@@%                                                                                                                                                     \n"
    "ENTER\n"
    "STRING                                        @@@@                                                                                                                                                             \n"
    "ENTER\n"
    "STRING                                                                                                                                                                                                        \n"
    "ENTER\n"
    "STRING                                                                                                                                                                                                        \n";

#define BADUSB_BUILTIN_SCRIPT_LEN (sizeof(badusb_builtin_script) - 1)

#endif
